### ISSUE TITLE
Ingredients without exact amount specified

### ISSUE THREAD

**Issue by therealschimmi** [vabene1111/recipes#111]
Can we handle those basic ingredients like salt, pepper, oil, etc. in a better way? I can't always tell the exact amount for salt and pepper or oil for frying needed. Many recipes online also just list those in different ways. However those need to be in the ingredient list so I can verify I have oil at home before going shopping.
What I thought of doing is putting a header after the main ingredients and just list what else is needed below with amount and unit left empty, that way it might even be a fancy utensil that's required. This is not possible atm. What do you think?

**Comment by vabene1111** [comment]
If you use 0 as the amount it will just show the ingredient in the view page :)

Is that sufficient or any better ideas?

**Comment by therealschimmi** [comment]
techincally that is a way to do it, but I don't like having an ingredient with 0 amount and whatever is the standard unit, just looks weird :) rather nice-to-have request really

**Comment by vabene1111** [comment]
ok, i know its a bit of a janky solution. The problem is the limited sice of the ingredient table. If i add other fields (for example a checkbox) it becomes bigger and bigger and less usable on mobile.

I am planning on refactoring the complete recipe editing workflow, when i do that i will find a clean and more obvious solution for this problem, but that will take a while since its a complete rewrite of that view and some other stuff comes first
