### ISSUE TITLE
category and easy tag filtering

### ISSUE THREAD

**Issue by benoni280** [vabene1111/recipes#112]
I find it difficult to quickly filter recipes through tags.

Perhaps a feature can be added, i see in more recipe websites.
Categories:
these categories can be linked, one to many, to the tags.
per example:
category: "meal type" > tags: breakfast, dinner, dessert
 or
                "cuisine" > tag: asian, italian,...
                "feeling like" > "pasta", 'pizza', "bbq"
  
and in the main recipe area, the categories could be made visible in a side menu that can list the tags, which you can easily select for filtering.

Also can we make the tags in the cookbook a link?
when selecting it filters on that tag.

Thanks

**Comment by vabene1111** [comment]
thanks for the feedback. i actually had categories in there at some point but removed them since tags can do anything categories could do but more. 

But you are right, it is not really intuitive/fast to search for tags, clicking on them would be cool but i will need to look at django-filters on how to do this with url parameters (also related to #5).

The second thing, some kind of quick filter side menu, would probably also be very nice. The problem here is that i dont really know how to nicely integrate it to the search page without looking weird on mobile, but this can probably be figured out. 

Overall nice suggestions, will take a look at it, maybe when working on #105

**Comment by vabene1111** [comment]
maybe keywords could have an attribute "quicksearch" that would show them in some kind of quick filter on the front page.

**Comment by benoni280** [comment]
This could be the use of category.
Every category will be added to the search filter "quick search" and show every tag that is linked to that category.
This way you control wat is visible and are able to sort the tags per category.

For mobile I attached some screenshots from a Dutch site I like[Image.jpeg][Image.jpeg]

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: vabene1111 <notifications@github.com>
Verzonden: Monday, June 15, 2020 11:39:25 AM
Aan: vabene1111/recipes <recipes@noreply.github.com>
CC: benoni280 <ben.vandentroost@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [vabene1111/recipes] category and easy tag filtering (#112)


maybe keywords could have an attribute "quicksearch" that would show them in some kind of quick filter on the front page.

**Comment by vabene1111** [comment]
i think i know what you mean .. i will think about this, i dont really feel like implementing a whole new system to achieve this kind of functionality, maybe i can abuse tags in some way to make this possible.

**Comment by smilerz** [comment]
> i think i know what you mean .. i will think about this, i dont really feel like implementing a whole new system to achieve this kind of functionality, maybe i can abuse tags in some way to make this possible.

I'm playing with modifying keywords to be hierarchical (utilizing django-treebeard) so that a faceted search could be added.  keywords now work on the admin page in my fork [here](https://github.com/smilerz/recipes).

In order to make facets work a search engine is likely going to be necessary, once I figured out how to do it I was going was going to ask about choices available or if you were even open to adding it.

**Comment by vabene1111** [comment]
thank you very much. I like the idea. Just two things to consider

- im am currently rewriting lots of thigs because i am implementing multi tennant support. This will be public in about a week or two but until then i dont want to change much at query/model level because it just messes up things again. There have been code changes in almost every file.
- the search is supposed to be refactored to a vue.js based page which means the search engine will need to be accessible via the api. This is most likely the case anyway but just so you have that in mind.

Feel free to play around with the search a bit and let me know if you need any help/feedback

**Comment by smilerz** [comment]
> * im am currently rewriting lots of thigs because i am implementing multi tennant support. This will be public in about a week or two but until then i dont want to change much at query/model level because it just messes up things again. There have been code changes in almost every file.

Good to know - it shouldn't' be an issue though as the tree model was fairly plug and play once I figured out how it worked.

**Comment by vabene1111** [comment]
i think this is now obsolete with the new tree based keywords
