### ISSUE TITLE
paprika import

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#123]
import for paprika exports (if they have any)

**Comment by FunWithUrban** [comment]
Just to add some info for this Paprika seems to offer two ways to export. The first one gives you a single file in a .paprikarecipes format and when you click on it Paprika opens and it starts importing that way and the other way is to export to HTML. You get a folder with each recipe as its own HTML file with the images saved and indexed. The website importer doesn't work obviously because its basically a local file if I understand it correctly but Its formatted really simply so idk if there's a way to convert it something else or upload it somewhere so recipes can pick it up? Here's how it looks in chrome.

![SpqYULq](https://user-images.githubusercontent.com/73844982/98029489-946bc200-1ddd-11eb-9c68-e72811167abb.png)

**Comment by vabene1111** [comment]
there is definitly a way to do this. If you have them laying around feel free to upload both files as samples here for future me (or someone else) to figure this out more easily

**Comment by FunWithUrban** [comment]
Here's a zip with both options exactly as its given to you with three different recipes inside.
[Paprika Export.zip](https://github.com/vabene1111/recipes/files/5484653/Paprika.Export.zip)

**Comment by vabene1111** [comment]
a basic paprika import has been added with the next release. It does not support images but that could be added later.

**Comment by vabene1111** [comment]
image support was now added.

**Comment by jt196** [comment]
@vabene1111 just playing around a little bit with this today. Couple of points:

1. Line breaks aren't importing. Looks like the Paprika html file has a special line class instead of <br> it uses <p class="line">. Hopefully this is an easy fix - and pretty essential in being able to read the recipe! It would be nice if each paragraph was imported to a step, but I can live with just line breaks. I've tried adding a `<br>` tag to the html, deleting the `class="line"` bit but the breaks are still not there. 
2. I'm working with an older version of Paprika and the html is formatted slightly differently, causing importing to break. I think it's just metadata so should be an easy fix. 
The older file metadata looks a bit like this:
```html
<b>Prep Time: </b><span itemprop="prepTime">30 minutes</span>
<b>Cook Time: </b><span itemprop="cookTime">4 hours</span>
```
The newer file metadata looks like this: 
```html
<b>        Prep Time        : </b><span itemprop="        ">        20 min        </span>
<b>        Cook Time        : </b><span itemprop="        ">        1 hr        </span>
<b>        Difficulty        : </b><span itemprop="        ">        Medium        </span>
<b>        Servings        : </b><span itemprop="        ">        Yield: 4 to 6 servings        </span>
```
Deleting the camelCase "prepTime" and "cookTime" metadata gave me a successful import, maybe you can get that Python script to just ignore this metadata? Here's the html export. There's some other weird stuff in the new version of the export html like spacing before and after the image links, but this didn't make any difference. 

[Easy DIY Liquid Castile Soap.txt](https://github.com/vabene1111/recipes/files/6009985/Easy.DIY.Liquid.Castile.Soap.txt)

**Comment by vabene1111** [comment]
Thanks for the feedback. Sadly the paprika export format is pretty crappy. They try to use itemprop which is meant for microdata but they implement it in a way that normal microdata parsers dont work. 

Maybe i can upgrade the parpika parser at some point to include the metadata as well or maybe paprika fixes their export format to actually contain the correct definitions.

I will add the other apps that dont have importers yet first but after that might take another look at paprika. If you are familiar with python feel free to take a look at cookbook\integrations\paprika.py where the importer lives :)

**Comment by jt196** [comment]
A little familiar with Python - will have a look and see. Cheers.

**Comment by jt196** [comment]
Just to say, the older format with the camelCase field is just broken, it won't work unless the field is empty like the newer files. So it doesn't need the metadata, it just needs to ignore the lack of camelCase. I'll have a quick look and see if there's something in there I understand...

**Comment by jt196** [comment]
A brief look at this - sorry not up to full debugging level yet - and it looks like some lines from the *recipe_url_import.py* file that are breaking this. The camelCase _prepTime_ and _cookTime_ itemprop properties in the older file are causing the parser to run this code through these loops. In the newer Paprika files, they don't have these properties. It's about as much as I can do at this point as I don't know whether your _prepTime_ and _cookTime_ are used in any other imports. Possibly they are, which is why this is breaking the import. 

```Python
    if 'prepTime' in ld_json:
        try:
            if (type(ld_json['prepTime']) == list
                    and len(ld_json['prepTime']) > 0):
                ld_json['prepTime'] = ld_json['prepTime'][0]
            ld_json['prepTime'] = round(
                parse_duration(
                    ld_json['prepTime']
                ).seconds / 60
            )
        except TypeError:
            ld_json['prepTime'] = 0
    else:
        ld_json['prepTime'] = 0
```

I think it's these lines that are breaking the import of the older Paprika recipe files: 
```Python
                parse_duration(
                    ld_json['prepTime']
                ).seconds / 60
```

**Comment by vabene1111** [comment]
perfect, thanks for all the pre work, i will take a look when i can find to do it

**Comment by jt196** [comment]
Here's the debug message I was getting by the way: 

<details><summary>UNHIDE</summary>
<p>

```
Environment:


Request Method: POST
Request URL: http://192.168.1.77:8493/import/

Django Version: 3.1.6
Python Version: 3.8.7
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django_tables2',
 'django_filters',
 'crispy_forms',
 'emoji_picker',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/recipes/cookbook/views/import_export.py", line 40, in import_recipe
    return integration.do_import(request.FILES.getlist('files'))
  File "/opt/recipes/cookbook/integration/integration.py", line 90, in do_import
    recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
  File "/opt/recipes/cookbook/integration/paprika.py", line 30, in get_recipe_from_file
    recipe_json = find_recipe_json(md_json['properties'], '')
  File "/opt/recipes/cookbook/helper/recipe_url_import.py", line 197, in find_recipe_json
    parse_duration(

Exception Type: AttributeError at /import/
Exception Value: 'NoneType' object has no attribute 'seconds'
```

</p>
</details>

**Comment by Syfaro** [comment]
If it's helpful at all, the .paprikarecipes file isn't that exotic, and can probably be parsed significantly easier. It's a ZIP file containing many .paprikarecipe files, each of which are gzipped JSON data.

Here's the outline of one of the JSON files (data omitted but types should still be clear): 

```json
{
  "photo_large": null,
  "created": "",
  "rating": 0,
  "notes": "",
  "photo_data": "",
  "photos": [],
  "uid": "",
  "cook_time": "",
  "prep_time": "",
  "photo": "",
  "description": "",
  "photo_hash": "",
  "directions": "",
  "servings": "",
  "difficulty": "",
  "total_time": "",
  "source": "",
  "ingredients": "",
  "image_url": "",
  "nutritional_info": "",
  "hash": "",
  "name": "",
  "categories": [],
  "source_url": ""
}
```

The `photo_data` field contains a base64 encoded JPEG image. 

You could parse it with something like the following:

```python
import sys
import io

import zipfile
import gzip
import json
import base64

# Usage: python paprika.py Export.paprikarecipes
with zipfile.ZipFile(sys.argv[1]) as z:
    for recipe_name in z.namelist():
        print(f'Reading recipe {recipe_name}')
        recipe_bytes = z.read(recipe_name)

        # gzip.open assumes that bytes are a filename, not data to be read,
        # so we need to make it IO-like.
        recipe_data = io.BytesIO(recipe_bytes)
        with gzip.open(recipe_data) as data:
            recipe = json.load(data)

            # If there's photo data, extract it into a non-encoded form and
            # remove from the original recipe so it doesn't take over the
            # entire screen when printing.
            if photo_data := recipe.get('photo_data'):
                photo = base64.b64decode(photo_data)
                del recipe['photo_data']

            print(recipe)
```

**Comment by vabene1111** [comment]
it gzipped 🙈 i thought it was some kind of stupid proprietary binary format 😂 that would make parsing that definitly much easier than the html files.

**Comment by vabene1111** [comment]
From the next update on the importer will use the paprikarecipes file and should work much more reliable

**Comment by jt196** [comment]
@vabene1111 - just having a bit of a play around with the Paprika file import in the beta release. Looks like it's working much better, including images, which is a huge improvement. Great job! 

A couple of things that are missing which if imported would make me think seriously about migrating, some of them already have existing fields in the Tandoor data, so I guess just need mapping. Others not much so. I've currently nearly 600 recipes in Paprika, so manually adding this would be a lot of work! 

- **Categories > Tags** (currently the import has an 'imported' tag, but all my category data in Paprika is missing)
- **Description > Description** (this doesn't seem to be imported)
- **Notes > Comments** (I'd love to see the notes section in the Paprika file imported as the top comment on the Tandoor recipe, not sure how easy it would be to do this but it'd be a good way to preserve the data)
- **Prep time/cook time > Prep/cook time** (not imported)
- **Servings > Servings** (defaults to 1 serving)
- **Source** - it'd be nice to retain the source URL and/or text, or even have this in the inline text as a reference like the nutrition data is currently, and source is done during a URL import. 
- **Nutrition** - seems to be imported into the bottom of the recipe. TBH this isn't a bother for me as I don't use the field a lot.

**Comment by vabene1111** [comment]
thanks for the feedback. Good timing, i am just having some trouble with the beta release but maybe your platform is already updated.

I am going to move your feedback to a new issue "paprika improvements". On the first round i tried to get as many importers to work as possible and might have left some information out. I will see what can be done regarding your feedback
