### ISSUE TITLE
English Translations 

### ISSUE THREAD

**Issue by cowenby** [vabene1111/recipes#135]
### Version
0.9.2

### Bug description
Just got it installed and running. I knew next to nothing about a week ago, but managed to get it installed on a Raspberry Pi 4. However, I have found a couple locations that didn't quite translate to English correctly:
First one is the drop down on a recipe page to edit it. 
Second one is on the default screen ("Log In to view recipes" is spelled wrong.) 

![Annotation 2020-07-12 231128](https://user-images.githubusercontent.com/33045633/87267275-2baab380-c495-11ea-9425-bba997d946ef.png)

**Comment by vabene1111** [comment]
yes, this has been fixed but due to the recipe step rewrite taking a little longer and my time for the project being a little short atm the update has not yet been published. You could switch to development branch which is pretty stable but there will be stable realease in the next few weeks that fixes it as well.

**Comment by vabene1111** [comment]
if you find any other spots that i missed please feel free to report them so i can fix them

**Comment by cowenby** [comment]
No worries. Given the current turmoil, being a bit short on time right now is a good sign.

I haven't seen any others yet but will let you know if I do.
