### ISSUE TITLE
Improve install process

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#143]
improve install instructions so its not so easy to forget stuff like .env or nginx.d 

ideas by @tdvantine in #140  https://pastebin.com/VDmXK7Dt

**Comment by NessInOnett** [comment]
I agree, some improvements could be made to the installation process.  I haven't tested this project out yet, just exploring what self-hostable software is available for recipe management.  Installation had me hung up for a bit

**Comment by vabene1111** [comment]
can you explain what exactly caused you difficulties ? the problem with writing a software is that you always know how everything works and thus its hard to see where others might have difficulties ?

Also please tell me if you had experience with docker before.

**Comment by NessInOnett** [comment]
Nothing major.. just maybe add more complete steps. 

I'm familiar with docker.. less so with docker compose.  I use it for a couple of services, but most of my stuff uses regular docker.  I just think the documentation could benefit from more of a step-by-step process.   

> Choose one of the included configurations here.

> **<choose one, and then what?>**

> Download the environment (config) file template . . . . 

I plan to install the software tomorrow, and I expect what I'll end up doing is cloning the entire repo, cd'ing into the configuration directory of my choice (plain), and proceeding from there.  I don't know for certain if that's the correct way to do it, but I'm sure it will work.   That's where I think extra instructions could be helpful.

I checked dockerhub to see if I could use that instead of docker-compose.  The package is available there, but no documentation at all and no mention of which configuration flavor it is (plain, nginx-proxy, etc) .. so I came back here to re-read the docker-compose instructions.

**Comment by tdvantine** [comment]
If you look at the pastebin above you should get a general idea of how the process works. Those instructions are based off a different style of deployment (zip files) but if you have a GUI easy peasy, CLI is a little more "fun" but not hard.

**Comment by vabene1111** [comment]
Ok, thanks for the feedback. I personally alsways use docker compose as its (for me at least) just a clean and simple way to store the configuration of my containers. Generally a docker compose config can be converted into a docker command and the other way around if you know what each means. 

If you want to do a plain docker installation and setup the database and proxy container yourself than that should work without any problems. If you want you can even submit the exact commands so i can add them to the instructions.

**Comment by stewartadam** [comment]
> If you want to do a plain docker installation and setup the database and proxy container yourself than that should work without any problems. If you want you can even submit the exact commands so i can add them to the instructions.

I ended up doing this with Apache, and had issues because I wanted to run the software behind the reverse proxy under a base URL and not on a specific port. FWIW there's a small quality of life improvement for this scenario that would make a big difference: `STATIC_URL` and `MEDIA_URL` file URLs are currently not configurable via `.env`, meaning I can't get those files working under my base URL (which is set via the `SCRIPT_NAME` header) and I currently now have to maintain my own image.

```
diff --git a/recipes/settings.py b/recipes/settings.py
index e08b8c0..1bd2959 100644
--- a/recipes/settings.py
+++ b/recipes/settings.py
@@ -175,10 +175,10 @@ LANGUAGES = [
 # Static files (CSS, JavaScript, Images)
 # https://docs.djangoproject.com/en/2.0/howto/static-files/
 
-STATIC_URL = '/static/'
+STATIC_URL = os.getenv('STATIC_URL', '/static/')
 STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
 
-MEDIA_URL = '/media/'
+MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
 MEDIA_ROOT = os.path.join(BASE_DIR, "mediafiles")
 
 # Serve static files with gzip
```

This fixes it, I'm testing a few other things but will make a PR shortly :)

**Comment by vabene1111** [comment]
i think the soultion you choose looks very good and i dont see any downsides to this approach so feel free to PR and i will merge it for the next release.

**Comment by joshuamallow** [comment]
I'm no docker expert...I know just enough. I typically use Portainer to setup containers. I tried creating a stack using the plain compose sample, but couldn't get it working even when trying to embed the ENV options into the compose file.

Has anyone managed to get this running easily in Portainer or Docker Run?

**Comment by vabene1111** [comment]
with the latest documentation improvements and the new automatically mounted nginx conf i think the install process is quite good. I can obviously still be improved but for now i think its good.
