### ISSUE TITLE
Error 400 when importing recipes

### ISSUE THREAD

**Issue by maarten1055** [vabene1111/recipes#158]
### Version
Version: 0.10.1

### Bug description
I'm testing some websites we use for recipes but most don't seem to work despite all including the ld+json.

I get this message:
There was an error loading a resource!{"error": true, "msg": "The requested site does not provide any recognized data format to import the recipe from."}

Sites that don't work:
https://njam.tv/recepten/italiaanse-steak-tartaar
https://www.libelle-lekker.be/bekijk-recept/1418/balletjes-met-tomaat-en-mozzarella
https://www.colruyt.be/nl/lekker-koken/gegratineerde-aubergines-tomaat-mozarella

Sites that work:
https://www.mijnspar.be/recepten/frozen-smoothie-breakfast-bowl
https://www.ah.nl/allerhande/recept/R-R1185801/snelle-pad-thai

**Comment by vabene1111** [comment]
thanks for the feedback! Sadly basically all pages do something different with their ld+json so the parser has to account for many many edge cases. I will try to add the pages you said weren't working in the next release

**Comment by vabene1111** [comment]
ok so the first site had malformed json (linebreaks at non RFC compliant places) but that could be fixed easily. Same problem for page 2.

The third page does indeed contain ld+json but when requesting the page content with python reqeusts it just returns a pretty empty html with a reference to some javascript files so i think its not loadable without something that can execute the pages javascript.

The first two (and probably many others that contain linebreak in their json) will be fixed with the next release (might be a little while because i am rewriting the whole shopping list ATM)
