### ISSUE TITLE
Pictures missing from recipes after successful save

### ISSUE THREAD

**Issue by v6-cblais** [vabene1111/recipes#164]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.10.0

### Bug description

Attempts to save an image says it was successful but is blank on the Cookbook view and when opening the recipe again after saving. No error message is reported in regards to the picture.
![Error](https://user-images.githubusercontent.com/50639170/91335093-f08ee600-e79d-11ea-89bc-69e0f1f261c1.JPG)

**Comment by vabene1111** [comment]
so the images should be saved in the docker container under `/opt/recipes/mediafiles`. Please verify that the images are in this folder. if they are then this is probably an issue with the webserver not serving the /mediafiles directory properly. Please refer to the docker-compose examples where an nginx config for serving the mediafiles can be found.

**Comment by wuast94** [comment]
Have the same problem.. Pictures are in the folder and I used the nginx example added to my reverse proxy. Mounted the media files under /media in my nginx container

**Comment by vabene1111** [comment]
hmm i just tested this feature with the latest version on my server and everything appears to be working fine. 

If the images are in the mediafiles folder please check the link address on the broken images, if they point to `http://your.domain.com/media/recipes/<RANDOM UID>_<RECIPE ID>.png` then the application code itself is correct and it has to be something with the media serving (nginx) at least from what i can figure.

**Comment by v6-cblais** [comment]
Mine show as a 404 message with the path like https://sub.domain.com/media/recipes/68b393a5-7a4d-4aaf-87e7-3711801825bd_2.png

Attempting to open the pictures in a new tab gives a 404 from nginx

I tried moving the image to another directory and re-adding the pictures but there was no change other than the file name that couldn't be found. I don't know what might be wrong with nginx if it is loading everything else without error.

**Comment by vabene1111** [comment]
serving the mediafiles and staticfiles vs. serving the application are two completly seperate tasks as one is WSGI server (gunicorn) and the other are just plain files served by nginx. You can test this by setting `GUNICORN_MEDIA=1` in the .env (remeber to down/up the container afterwards) and all media files should serve. 

If you need further help you will need to post your folder structure, .env file and nginx config

**Comment by v6-cblais** [comment]
No change; I attached the configs you asked for (Basically defaults)
[RecipesConfig.txt](https://github.com/vabene1111/recipes/files/5136100/RecipesConfig.txt)

**Comment by vabene1111** [comment]
what is interesting (and you can visualize that for yourself a little better if you use the `tree` command) is that the one image you posted the link to lies in the /media/ directory directly and the other two are in /media/recipes (where they should be). 

Also there is a second config in the nginx/conf.d directory, i have no idea what it does there. I would personally recommend to put taefik and recipes in two distinct recipes so nothing overlaps here.

please also try if https://sub.domain.com/media/recipes/abb34f83-6cc5-484c-8140-a06c3d9ab5fc_3.png works as that is one of the images in the recipes folder. How did the `68b393a5-7a4d-4aaf-87e7-3711801825bd_2.png` end up where it is, did you move it manually for testing ? 

If nothing here works i think we might try getting on a discord or jitsi or whatever call and looking at your install together, because i am kinda running out of ideas 🙈

**Comment by v6-cblais** [comment]
Sorry; I should have removed that; that file is there from testing. 

A call would be great! Thanks!

**Comment by vabene1111** [comment]
would discord work for you ? if so just add me `vabene1111#5492` write me a twitter dm or something so we can shedule a time that works for both of us (i am CEST timezone)

**Comment by vabene1111** [comment]
´so after a lot of looking we were able to fix it. We dont really know what exactly was the root cause of the issue but

- the recipes config was in a big `docker-compose.yml` with many different services as well which might have messed up the named routing
- traefik wasn't properly forwarding requests to nginx

**Comment by vabene1111** [comment]
This is usually a setup issue. Please look at the FAQ and some of the other issues regarding this topic. Make sure you follow the install guide.

**Comment by smilerz** [comment]
> Any more insight into this issue? Im currently experiencing the same behavior. images are saved in the recipes folder successfully but getting a 404 on serve. had more services in my docker-compose.yml but i commented them all out and am still seeing the same issue. any more details on the request forwarding fix? @vabene1111

If you are getting 404 and have confirmed that the file exists in the media folder then your reverse proxy is setup incorrectly - the following headers need to be present and correct under the System page.

```
HTTP_HOST:my.tld.com  # +:XXXX - port if applicable
HTTP_X_FORWARDED_HOST:my.tld.com
HTTP_X_FORWARDED_PROTO:https
HTTP_X_SCRIPT_NAME:/recipes  #optional if using subfolder configuration
```

**Comment by JM-Lemmi** [comment]
I am having the same issue.

Docker container, v1.4.5, Ref: 4e13fb3b8cdee2f9f6f1e1d2f9c29d4b77c4d50a

But I think I found the issue. The nginx config for the container looks for the files in `/media/`, but the actual image file is at `/opt/recipes/mediafiles/`

https://github.com/TandoorRecipes/recipes/blob/4214ef4a9f3bf18d3caf63b8f19bb81a6b14b086/nginx/conf.d/Recipes.conf#L7-L10
