### ISSUE TITLE
Client-side input validation

### ISSUE THREAD

**Issue by stewartadam** [vabene1111/recipes#171]
**Is your feature request related to a problem? Please describe.**
As of writing (v0.10.1) there doesn't appear to be input validation during web recipe import, possibly elsewhere. The quantity field in of an ingredient row, for example, accepts non-integer numbers when server-side validation enforces integer values only for that field.

In such a mismatch, the server creates a partial recipe entry (up through the ingredient row that contained the validation error) and presents an error to the user without much detail unless DEBUG=1.

**Describe the solution you'd like**
Client-side validation enforces similar input limitations to server-side validations, to prevent users from submitting recipes that fail to import/save.

**Comment by vabene1111** [comment]
Interesting issue, thanks for reporting! I do not really care about client side validation as long as the server gives appropriate answers and does not create any partial database entries so i will probably stick to the server doing validation but the issues you describe are definitely bad and should be fixed!

Also the reason for no number validation being used on the input field is so that you can use both the `,` and the `.` as a decimal seperator and the server tries to match it to an integer.

**Comment by vabene1111** [comment]
The issue will be fixed in the next release and its also no longer possible for partial entries to get created as the whole function is now wrapped in a database transaction that gets rolled back if an error occurs. Errors do still break the client side but that on purpose so that it can be fixed asap if something occurs.
