### ISSUE TITLE
Disabling amount can result in integer validation errors

### ISSUE THREAD

**Issue by stewartadam** [vabene1111/recipes#180]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.10.1

### Bug description

When adding/editing a recipe, selecting "Disable Amount" sometimes results in a validation error upon saving the recipe:
![image](https://user-images.githubusercontent.com/77808/93732892-4af64900-fb88-11ea-8a8c-37dd867f0f7b.png)

I believe this happens if the quantity/unit fields were focused before selecting disable amount. Filling the quantity field with any integer value then disabling amount again for that ingredient works.

**Comment by vabene1111** [comment]
I have tried to reproduce this issue but i can only do so by purposely typing some letters into the amount field (which i guess makes the error valid). Can you try to investigate this further and see which normal behavior is causing this issue ?

One option would be to just always set the amount to 0 whenever the amount is disabled. I didn't want to to this because if you have a amount entered and then disable it (possibly by accident) you loose the data stored there before.

**Comment by stewartadam** [comment]
I double checked and it happens if I clear the field. Easy fix would be to coerce `''` or `None` to 0.

**Comment by vabene1111** [comment]
ah ok, thank you, that can definitely cause it. Will see how to fix it.
