### ISSUE TITLE
Servings

### ISSUE THREAD

**Issue by eTaurus** [vabene1111/recipes#197]
I would like to be able to specify how many servings a recipe yields. The best solution would be to be able to specify it in the "recipe scaler" directly and adding "servings" after the number. This way it would be possible to scale it from e.g. four to six servings.

A good example is the german website [chefkoch.de](https://www.chefkoch.de). I cannot find an english website with this functionality. 

![grafik](https://user-images.githubusercontent.com/24603992/95650171-1e2bb680-0ae2-11eb-83d2-8363c767a05c.png)

Thank you for this fine piece of software! I sent a request to join as a translator over at transifex.

**Comment by vabene1111** [comment]
there is actually an open PR and discussion about this topic. When i started this application i purposely left out servings because i disliked the concept as everyone eats different amounts and serving (for me at least) are very often misleading. Even the same recipe will sometimes be enough for different amounts of servings as hunger varies form day to day. 

using the application over time i noticed that i wanted to have this feature so i added the "cook log" feature were you could add a servings amount per "cooking event". This has yet to be displayed somewhere and i am not 100% happy with that solution either. 

Servering definitely need to be "per User" and not per recipe, maybe one could add a default serving and some kind of "note" field to the recipe and the cook log servings would override the default serving count for the user. 

Definitely a topic that needs to be looked at but one i really want to do properly as i dislike the concept of servings the way its done on most websites/in most recipes.

**Comment by eTaurus** [comment]
Okay, found it. I did not check open PRs, I only searched in open issues. I close this issue, will follow the PR and wait for the solution you come up with. Maybe I am going like it.

**Comment by vabene1111** [comment]
na its fine, if its in issues its more likely to be seen, no worries. also disussions are better done in issues in my opinion

**Comment by koch17** [comment]
This is probably the only missing feature for me. I like the way tourn suggests in the PR, not sure about the implementation especially for when you have something like 1/2 spoon or cup of something for 5 servings, how to properly adjust it to 7 servings? 7/10 of a spoon will be weird, but from another side, maybe it can be rounded to 1/4, 1/2 or 3/4 spoons or cups?

**Comment by vabene1111** [comment]
i like the pull request very much as well, i just need to address the issues mentioned above. 

If servings should be the amount of servings or a multiple of the normal amount can be decoupled and i think i would leave it to the user to decide (make a setting) as i personally prefer scaling recipes instead of servings (just the way i calculate it in my head)

**Comment by CorneliousJD** [comment]
Chiming in on this, I would like both scaling recipes and servings to both be present.

Scale recibe by X or select the number of servings. If we enter that a recipe makes 4 servings and want to make 6 servings, then it scales by 1.5
If we want to make 7 servings it will scale by 1.75 
Right now you can easily do the math and scale it manually, but having an actaul entry in the recipe for "servings" that you can enter and scale by that is also great. Users who do NOT want to use "servings" can simply leave it out, and it will continue to funciton exactly like it is. 

I think that (personally) will be the best way. Right now serving # is probably the one big thing IMO that's missing here that OpenEats has

**Comment by vabene1111** [comment]
Will be implemented in the next release
