### ISSUE TITLE
generic docker compose

### ISSUE THREAD

**Issue by palitu** [vabene1111/recipes#21]
Is it possible to have a generic compose file, which just build and presents the UI over a specific port?

This should ease the testing of it, and allow for simpler local deployments, without having to have a seperate NGINX container.

cheers

**Comment by vabene1111** [comment]
do you want that for testing only or for actual deployment ? 
Because for testing i think `manage.py runserver` should suffice, otherwise it should be just a matter of removing the nginx container and network config right ?

maybe we should have a wiki with some samples of docker-compose setups for different usecases

**Comment by palitu** [comment]
Ah, yes i see.  I was tired!

I think a couple of composes, potentially just the generic one would work..

cheers.

**Comment by vabene1111** [comment]
I guess, together with #16, i will have to take a look on how to organize the project structure a little better.
