### ISSUE TITLE
Bug Report - Meal Plan on Sundays not saving

### ISSUE THREAD

**Issue by dwtaylornz** [vabene1111/recipes#231]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Current Version: 0.11.1

### Bug description
Meals dragged onto a meal plan on a Sunday do not save, also If i drag meal onto any Sunday (future) it does not save. 
Every other day )mon - sat) saves without issue.

**Comment by sebimarkgraf** [comment]
Hey @dwtaylornz 
I guess I am having the same bug as you. But since I am using different devices it seems to be caused by the language settings.

Could you confirm if sunday is the first day in your week?

Using any language setting that moves the sunday as last day in the week works without problems for me, but e.g. en-us seems to have problems.

**Comment by vabene1111** [comment]
ah thats an interesting thing because i was not able to reproduce this and this would explain it. Will take a look at this hopefully soon

**Comment by dwtaylornz** [comment]
> Hey @dwtaylornz
> I guess I am having the same bug as you. But since I am using different devices it seems to be caused by the language settings.
> 
> Could you confirm if sunday is the first day in your week?

Hmm, Monday is the official first day of the week here in New Zealand. 
I'll have a play with language settings to see if that has any effect.

**Comment by vabene1111** [comment]
yes this is definitly related to the locale. If sunday is the first day of the week saving the entry fails.
