### ISSUE TITLE
Translations in javascript text are not escaped

### ISSUE THREAD

**Issue by sephrat** [vabene1111/recipes#262]
### Version
Version: develop (unreleased yet)*

### Bug description
I recently updated the French translations and suddenly the javascript is broken because of a syntax error. In this case, there is an apostrophe (quote) in the French string and it is interpreted by javascript.
![image](https://user-images.githubusercontent.com/34862846/102504559-49ea9000-4081-11eb-8d6d-0c70f1561bf5.png)

I'm not sure what the correct solution would be with Django. Ideally `<% trans %>` should have an option to escape special characters, this is how I worked around it in another framework. But it's not supported: https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#internationalization-in-template-code . 

Should we build our own function to escape translations? 
Otherwise I would escape all strings in Transifex directly. However it's tedious and not ideal, especially since I don't know whether the text is used in a template or python directly (I shouldn't escape quotes there). 

* by the way something puzzles me: you just released 12.0.1 earlier today and it doesn't contain the new translations from yesterday, or at least not the javascript ones. They are present in the repo though, I just pulled this morning and have this issue on my other install. Is there a missing `compilemessages` somewhere in the CI?

**Comment by vabene1111** [comment]
yes i forgot to run compilemessages .. this is not done trough the CI which it probably should .. i kinda need to automate the whole translation process but since i was never too happy with transifex i havn't done so yet.

I will need to look into escaping of translated strings. I guess one fix would be to use double quotes but that does not seem right. Usually in django there is a correct way of doing things, it sometimes just hides very well (and sometimes it turns out there isn't any) ..

**Comment by vabene1111** [comment]
From django doc it appears:

js is best localized using special javascript cataloges https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#module-django.views.i18n

**Comment by sephrat** [comment]
Ah stupid me, it was the item just below the one I linked. Nice finding!
Looks not so complicated, I can try something around in the next days and submit a PR if you like.

**Comment by vabene1111** [comment]
i am already on it and have it partially working but running out of time right now . .will continue in a few days.

**Comment by vabene1111** [comment]
ok so the currently commited solution provides route (e.g. `http://127.0.0.1:8000/jsi18n/`) that should contain all translations. 

For some reason it does not seem to find the translation files in the cookbook application and only the few that are in recipes. Maybe my project structure is wrong or deprecated 🤔 

If you want feel free to take a look, maybe i have missed something.

**Comment by vabene1111** [comment]
ok so the problem appears to be that django uses a different so called domain when translating javascript and python code. This is done to make the javascript catalog as small as possible.

It seems that i need to do this and therefor also setup a transfiex thingy so that the javascript strings get translated sepreatly.

https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#specialties-of-django-translation

for now i will try to set the domain of the javascript view to the same as the python code to get it working for the time being.

**Comment by vabene1111** [comment]
ok so i have added the new gettext method to all translated javascript code (at least in the vue.js heavy pages), this should make the french (and other similar) translations usable for the time being. 

As stated above i will need to figure out how to update the translations in a way that javascript stuff gets put into its own domain later.
