### ISSUE TITLE
Italian Translation (almost) complete

### ISSUE THREAD

**Issue by auanasgheps** [vabene1111/recipes#265]
Ciao,
I have noticed this app is not translated in Italian, then that was halfway done in Transifex. 

So I took the opportunity to complete it because I really like this app!

I'm almost done, is there a way to test it before merging? Otherwise you can already import it from Transifex. I'm sure there will be more tweaking as I still need to revise the previous work which wasn't _perfect_, but nothing major should be broken.

**Comment by vabene1111** [comment]
there is no real quality assurance process for translations as there mostly is only one person working on it. I guess just finish it on transifex and i will put it into the next release. 

If its broken after you update feel free to fix it, some translations are better than none and except for little issues with javascript nothing should be broken by localization (see #262 )

**Comment by vabene1111** [comment]
Also thank you very much, translations are always welcome as i cannot do them myself :)

**Comment by auanasgheps** [comment]
> there is no real quality assurance process for translations

I think we got lost in translation.
I meant I will do the QA, but will take time. I'm not a pro translator, but I've translated dozen of software and I know takes time to adjust the context of some strings.

As a fun and side fact, did you know that your nickname means "it's okay" in Italian? I originally thought you were Italian 😆

**Comment by vabene1111** [comment]
i did not really now what exactly it means but i have had some confusion over the years where people thought i was italian 😂 i mainly choose it because it sounded nice and i am not very creative (who would have thought with an application for recipes being called "recipes") ...

transifex will create a PR whenever all strings are translated. I think a bad translation is still better than none so i guess i will just keep the current ones in (already merged it) and when you get around to fixing it i will push another update. Maybe you will have it done before i get around to doing another update, pretty busy atm.

Thank you very much for spending your time trying to improve the translation, always happy to see new languages as it means new people will be able to enjoy the project.
