### ISSUE TITLE
Recipes cannot be viewed by anyone without a superuser account

### ISSUE THREAD

**Issue by redstonedesigner** [vabene1111/recipes#272]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.12.1

### Bug description

When attempting to load a recipe on a non-superuser account, it does not work and nothing can be loaded.  Inspection of the API reveals 403 (Forbidden) errors are being returned despite having all view permissions able to be given.

Edit: Further testing reveals all calls that are made with a non-superuser account are redirected back to the search page.

**Comment by vabene1111** [comment]
that is interesting, there are tests in place to verify that the permissions work but maybe something got messed up. I will test this and provide a fix, for now please use a superuser account as i currently dont have much time to work on recipes.

**Comment by cyberius0** [comment]
Yes I can confirm this. I added my first recipe. Added a second account for my wife via "Admin" panel. She only can see the picture and title of the recipe, but not the ingredients or cooking steps.

**Comment by vabene1111** [comment]
Ok that is interesting. What kind of setup are you running ? Because i have implemented some tests and they work (someone with only user or only guest permission can view anything related to recipes).

I have also tested it in my dev environment and in my production environment.

Did you add a Group to the users ? You do so trough the admin panel there is a group section where you can add "admin", "user" or "guest" to the user.

**Comment by redstonedesigner** [comment]
Groups have been assigned, I've even tried adding permissions to the individual users.

I'm running under Docker with the latest image pulled.

**Comment by vabene1111** [comment]
permissions are basically completly ignored as i only use model/view based permissions plus my own system for object level stuff. 

is this how your test user looks ? because this works for me and i dont really see how different installation setups could mess up the permission system 🤔 

![image](https://user-images.githubusercontent.com/6819595/103445418-fb89e380-4c73-11eb-8b62-756b9e0aec95.png)

**Comment by redstonedesigner** [comment]
![Image](https://pomf.redstonedesigner.com/files/qxslsp.png)

This is how mine is set up.

**Comment by vabene1111** [comment]
This is very interesting, you have different group names than i have. Were those groups created automatically or did you create/edit anything manually ? 

There is a migration that should create `guest`, `user` and `admin` and thats also what the permission system checks for.

**Comment by redstonedesigner** [comment]
I renamed the groups to make it easier for myself to understand what each group could do.

Are you indicating that the system checks for the group **names** rather tthan the **permissions** assigned to those groups?

**Comment by vabene1111** [comment]
yes that is exactly the case. Django useses names to identify groups (not IDs) and thus changing the name breaks the permission system. 

This is not really good from a technical standpoint but since the permssion system is very much WIP anyway it is the way it will be for a while ...

**Comment by redstonedesigner** [comment]
I've changed the group names back to "admin", "user" and "guest" and it seems to be functioning normally.

**Comment by redstonedesigner** [comment]
Having changed the group names back to the default ones, the issue appears to be resolved.

**Comment by vabene1111** [comment]
perfect 👍 

i will need to add some documentation or some checks somewhere i guess 🤔
