### ISSUE TITLE
Ingredients are shown twice

### ISSUE THREAD

**Issue by cyberius0** [vabene1111/recipes#286]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.12.1

### Issue
The ingredients, that I added, are shown twice: In the "heading" and in "Step 1" where I entered them. This looks like this:
![](https://i.ibb.co/t8q1RZn/firefox-2020-12-25-00-52-16.png)

But your example picture only shows the ingredients once:

![](https://i.ibb.co/BrW8gzw/firefox-2020-12-25-00-52-26.png)

So what am I doing wrong?
I have no other way than adding the ingredients via the "steps" field. I can only choose between type "time" and "text". My current workaround is to put the step where I added the ingredients to the bottom.

btw, your screenshot doesn't include that big header "Anleitung" before the cooking steps. Can i disable this header?

**Comment by vabene1111** [comment]
You are actually doing everything correctly AND the behavior you are observing is intended.

Steps are meant for large recipes and since i often use my phone in the kitchen i dont want to scroll up to the ingredients and then back down to the instructions. Thus all recipes that contain more than one step will show the ingredients at the top (as an overview) and also the ones that belong to each step.

I am thinking about adding some way of adding ingredients into the text, that would allow to disable the double display but for now this is the best option.
