### ISSUE TITLE
Ingredients should never be silently dropped

### ISSUE THREAD

**Issue by jakobwenzel** [vabene1111/recipes#323]
### Version
Version: 0.13.0

### Bug description
While Importing a recipe, Ingredients that cannot be parsed are _silently_ dropped. There should be at least some sort of notification this happened.

**Comment by vabene1111** [comment]
ok this is definitly not something that should happen. 

The old parser simply put everything into the "food" field. I guess now that the notes field is there too we could use that.

**Comment by jakobwenzel** [comment]
I fixed the immediate cause in 29903af085a515233120d27fa92505fa16d9fb90, but with that complex control flow in `parse()` I reckon it's going to happen again sooner or later...

Maybe an else at https://github.com/vabene1111/recipes/blob/566eea1d753f37e8f7765a290a492bfa8d597803/cookbook/helper/recipe_url_import.py#L75-L77

**Comment by vabene1111** [comment]
i just fixed the issue by adding the old "secondary" branch where everything is put into the food when all other parsing attempts fail

78fa5338d3a10864a4e342183b4b216f1f9937b1

because as you say, no matter how much we improve the parser, there are going to be cases where it fails and we want a backup strategy (there are just infinity many (stupid) ways different pages handle recipes)
