### ISSUE TITLE
clear steps to setup docker with sqlite3?

### ISSUE THREAD

**Issue by somedevreally** [vabene1111/recipes#360]
am trying to setup docker with sqlite3, searched existing issues didnt find any solution

in .env i have setup db engine
`DB_ENGINE=django.db.backends.sqlite3`

and in docker-compose i have setup the 
```
volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
      - ./staticfiles:/static
      - ./mediafiles:/media
      - ./db.sqlite:/opt/recipes/db.sqlite
```
but the data is not saved, when the container is stopped and re-created.
do i need to add anything more in .env file?

thanks, recipes is great application.

**Comment by cesarblancg** [comment]
If you see this [line](https://github.com/vabene1111/recipes/blob/develop/recipes/settings.py#L147), the default name for the file will be the "POSTGRES_DB" value in the env file. You can just let it empty and use the default "db.sqlite3"(you are using "db.sqlite").

**Comment by somedevreally** [comment]
great, changing db.sqlite to db.sqlite3 in docker-compose helped. thank you.

any drawback of using sqlite instead of postgres?

**Comment by cesarblancg** [comment]
If you will create a little app, you can use sqlite, but for large projects, have less performance and don't allow concurrency. 

More info [here](https://tableplus.com/blog/2018/08/sqlite-vs-postgresql-which-database-to-use-and-why.html#:~:text=The%20SQLite%20library%20is%20less,is%20much%20larger%20in%20size.&text=SQLite%20stores%20the%20database%20in,located%20anywhere%20in%20the%20directory.&text=PostgreSQL%20is%20only%20portable%20after,can%20be%20a%20hassle%20sometimes.)

**Comment by vabene1111** [comment]
There are also certain features (like the fuzzy search) that are only supported by postgresql so i recommend using that, but its defintly not required

**Comment by schlamar** [comment]
@vabene1111 Is there a complete overview of all restrictions if using SQLite instead of PostgreSQL?

IMO SQLite is the perfect choice for self hosted applications with just a few users. It makes administration and maintenance so much easier. 

Please see https://www.sqlite.org/whentouse.html 

> SQLite works great as the database engine for most low to medium traffic websites (which is to say, most websites). The amount of web traffic that SQLite can handle depends on how heavily the website uses its database. Generally speaking, any site that gets fewer than 100K hits/day should work fine with SQLite. The 100K hits/day figure is a conservative estimate, not a hard upper bound. SQLite has been demonstrated to work with 10 times that amount of traffic.

Generally, a lot of projects in this area focus too much on a perfect deployment scenario while it is unnecessary for almost every deployment. Sadly, one of the most important points in the Zen of Python is pretty much ignored when it comes to deploying Python WSGI applications:

    >>> import this
    The Zen of Python, by Tim Peters
    ...
    Simple is better than complex.

Sorry, I know this isn't the fault of this project as there is no simpler officially supported and recommended solution here than Gunicorn -> NGINX as soon as a WSGI application hits the public internet (or at least I do not know of). My intention with this comment is the hope, that it just slightly shifts the focus towards simpler deployments for the future.

**Comment by vabene1111** [comment]
thanks for your feedback. I try to keep it as simple as possible as it saves me a lot of work and for me postgresql is actually a very convenient setup method. 

That said at the moment the only features that are missing are the fuzzy search filters that rely on the postgres backend system to do the heavy lifting. That means that you will have to use exact parts of the recipe names instead of the TrigramSimilarity search that postgres offers.
