### ISSUE TITLE
Can´t write "1/2" or "half" in recipe amount.

### ISSUE THREAD

**Issue by Tangogr** [vabene1111/recipes#47]
Just numbers... I can´t write "1/2" in ammount, and "spoon" in units... Neither "1/2" or "half", etc.

![image](https://user-images.githubusercontent.com/9417423/78612267-338d0300-7869-11ea-9c8f-427e4ab148b2.png)

**Comment by vabene1111** [comment]
its not supposed to present you with an error page but its also correct that it does not accept the input. 

The amount must be an number, formatted as either `0.5` or ``0,5`. This is so that the ingredient calculator can scale up or down the ingredient amout. If you could enter whatever you want the calculator would not know how to multiply `half` with a number.

I will see that i make this clear in an error message.

**Comment by Tangogr** [comment]
Oh! Great! That has its logic. 

There is no problem using "0.5" instead "half" or "1/2" or whatever. 

"The one that doesn´t know, is blind"

**Comment by vabene1111** [comment]
No problem, but there definitely should be a helpful error message instead of a stack trace, so good thing you pointed it out :D
