### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [vabene1111/recipes#549]
https://translate.tandoor.dev/projects/tandoor/#information
says "proprietary"

Should be AGPLv3+.

Why the commons clause is in https://github.com/vabene1111/recipes/blob/develop/LICENSE.md I don't know.

**Comment by vabene1111** [comment]
That is actually intended at the moment. I am currently in work with an attorney to figure out what license fits this project best.

The reason for this is that i have spend thousands of hours working on this project and while i want to maintain free and unlimited access to this application for personal use and self hosting I do not want any big company to just take the application and sell it as a hosted service (thats what the common clause exception intends but probably does not fully do). Basically the same considerations that MongoDB and others made when switching to their source available licenses.

I hope to get this resolved within the next few weeks and then change the license accordingly. 

But thank you for reporting this, overall it would be really interesting for me to know if this licensing option is something you would consider to be ok or not ?

**Comment by comradekingu** [comment]
@vabene1111 
The project is already licensed AGPLv3+. You need approval of every contributor to re-license it.

What is the Commons Clause attempting to do? The SSPL is AFAIK meant to be an addition of the sort to the existing AGPLv3.

I was going to contribute to the strings on WL, and "proprietary" just creates a mess of re-licensing.
Make it AGPLv3+ and call it good.

**Comment by vabene1111** [comment]
thank you for the feedback. I already know that approval is needed, thats why i am trying to get that sorted as fast as possible and already have obtained approval from major contributers. 

Some further explanations on to why the license is choosen the way it is can be found in the README and [here](https://github.com/vabene1111/recipes/issues/238).

i guess i will make the translations AGPL as they can basically be fully seperated from the application. Even if i re-license the application i can leave the translations AGPL as there is no use in them alone.

**Comment by comradekingu** [comment]
@vabene1111
My understanding is that you can't relicense AGPLv3+ into MIT. How the strings further combine with the app or other works as per the requirements of the AGPLv3+ is another matter. I wouldn't risk your interpretation.

Also https://translate.tandoor.dev/projects/tandoor/glossary/ is still "proprietary".

**Comment by vabene1111** [comment]
you are correct. I will leave it as AGPL for now. Honestly this whole licensing thing is a real motivation killer for me. most of contributors dont really care about it but in the end i spend so much time just figuring out how to license this stuff properly that i sometimes think going closed source/ or stopping development completely would be better. Dont get me wrong, you are completely right with your feedback as far as i can judge this but I did not start this project because i wanted to become a lawyer but because i love software development and i love to give this away for everyone to enjoy. 

When and if i change the license i will get permission from everyone who contributed and if there are any objections the contributions will simply be removed from the new version. 

As for you: If you deeply care about this stuff i recommend simply not contributing to this repository. There are plenty of people who do so just because they love to use and contribute to the application no matter how its licensed. It is a lot of work for me to remove stuff afterwards and there is most likely going to be a licensing change in the future (possibly to just AGPL but maybe also to something a little more restrictive). 

I do not feel like i am doing something that is unfair. I have spend hundreds if not thousands of hours working on this. Reserving me the right to be the one who might at some point get something back for this is something that i feel like is absolutely justifiable. I could have just from the beginning on developed this closed source proprietary and nobody would have had any benefits ...

**Comment by comradekingu** [comment]
@vabene1111
I am just trying to help out because you are using Weblate.
Also, https://github.com/vishnuraghavb/EnRecipes/pull/17 didn't go so well, so I am happy to try to make this the default recipe manager to the best of its ability.

To possibly save you some time by way of a summary of hours I have put into various things:

AGPLv3+ licensing means you don't need to loose rights, nor does anyone else.
If by "more restrictive" you mean more copyleft, the few licenses that I've seen aren't A/GPLv3 compatible, so that is a bit of a non-starter in terms of ecosystem compatibility.

You can add an exception for app-stores that aren't compatible with AGPLv3+. (I advice against it.)

Also, nobody is going to try to sell this without major contributions.
As a maintainer you can set up donations on Liberapay. https://liberapay.com/explore/teams

It has never happened (to my knowledge) that anyone tries to "fake" this, much less successfully.

uBlock / uBlock origin is maybe the only example to the contrary, but all in the doing of its maintainer.

**Comment by vabene1111** [comment]
Thanks for the input on this topic. My main concern is that something like Mongo DB happens (people put a lot of work into something and some big corp comes around and makes a lot of money of it)

I want to implement all features that are required for throwing this application onto a server and start selling it into the open source version as i believe that they can also be used by everyone who selfhost this. In general there wont be different versions of this software, everything that is available on the hosted version should be available in the self hosted one as well and vice versa. That means that everyone who can cheaply setup some infrastructure could take this application and start selling it just as i plan on doing (btw. i do not plan to rip anyone off, if you selfhosted you pay your server/electricity/time, i just want to offer a way to outsource that for a fair price).

In the end this will most likely never happen as this is simply way to small but i still wanted to have some assurance. Thats why the selling exception was added. 

I will consult with a lawyer in the next few weeks, if i find a good solution i might change the license to reflect that wish, if not the selling exception will most likely be removed and everything will be AGPL v3.
