### ISSUE TITLE
Synolgy NAS DSM7 Deployment Instruction

### ISSUE THREAD

**Issue by DiversityBug** [vabene1111/recipes#554]
Hello,

I LOVE YOUR PROJECT! GREAT JOB! 
I'm being consumed by it since stumbling upon and trying to educate on docker etc. in hopes to eventually replace the family's current very clunky solution.
I got the three containers working with your compose file and the instructions from #98 but think there might be a way to get everything working with a Synology GUI only approach. I would like to produce some Instructions on it so more peeps can easily enjoy your great work.

Hence some questions: (Please forgive me if they are simple, I'm still educating.)

1. I noticed the .env file is loaded for both containers. 
Are all variables required in the Postgres and web app containers?
If not, could you point out which belongs to which?

2. In Issue #96 you mention _'#79 is not very high on my priority list as 99% of setups don't require it.'_
I don't understand why tbh. 
I would think back up the data for your app e.g. to spin up another NAS & Docker in case the current one breaks. But understand just taking the local structure might not work as a good solution due to read/wirte when the backup is executed.

Cheers

**Comment by vabene1111** [comment]
thanks for the kind words, glad you like it. There are no stupid questions so no worries, here are your answers

1. the variables are mostly required by the application (web) container but all database variables starting with POSTGRES_ are required by the postgres container as well. It loads its default settings (which database to create with which users and passwords) from them
2. You are totally right, backups are important and i highly recommend making them. That said there are many solutions out there to make backups from containers. Because of that i decided to focus on new features and the code base instead of management functions which could be handled by tested tools. I recently started using this https://hub.docker.com/r/prodrigestivill/postgres-backup-local image for backing up the database. I really like it so far. I guess you could use that in combination with the synology active backup feature to create backups from the database. Also make sure to backup the /mediafiles/ directory as it contains the images. Other than that you could backup the most important data by exporting all recipes using the export feature. There will probably be a proper backup system in the future but there are some features that will be implemented before that. Just backing up the files from postgres is not recommended btw.

Hope that helps you, if you have any additional questions let me know.

**Comment by DiversityBug** [comment]
Attached the Synology UX only Deployment Instructions for your use.
[Install Tandoor Recipes on a Synology NAS.docx](https://github.com/vabene1111/recipes/files/6334771/Install.Tandoor.Recipes.on.a.Synology.NAS.docx)

**Comment by vabene1111** [comment]
thanks, i will get this into the docs when i have time.

**Comment by DiversityBug** [comment]
Thanks for the backup tip. Unfortunately, I get 'Missing POSTGRES_DB_FILE file' only even though the Env says the file is an alternative for POSTGRES_PASSWORD. Where would the format need to be and where to place it?

I found the option to export a recipe in the recipe view. Is there an export all option?

On another note, cleaning up some tags, ingredients etc. in the Admin Section does not seem to have any effect in the front end. How could that be?

I guess I would need to open a separate issue but, would it be possible to get a screen like Cookbook one but only showing recipes assigned to a certain book? Utensils and Books don't show them in the nice listing like the other screen.

Is it possible to add Fibre to the Nutrition currently?

**Comment by DiversityBug** [comment]
> I found the option to export a recipe in the recipe view. Is there an export all option?
There is by ticking the export all option below the one selected recipe to get them all zipped.

> On another note, cleaning up some tags, ingredients etc. in the Admin Section does not seem to have any effect in the front end. How could that be?
A better way to merge ingredients and manage keywords is through the UI.

**Comment by DiversityBug** [comment]
Attached the Synology UX only Deployment and Update Instructions for your use.
[Install and Update Tandoor Recipes on a Synology NAS.docx](https://github.com/vabene1111/recipes/files/6704193/Install.and.Update.Tandoor.Recipes.on.a.Synology.NAS.docx)

**Comment by vabene1111** [comment]
thank you and apologies for not yet merging this, been kinda busy with features and work related stuff .. hope to get to this soon

**Comment by vabene1111** [comment]
ok so I have decided that the word guide is so detailed and well written/structured that it is linked as the complete document and not converted into markdown. Thanks very much @DiversityBug I am sure this will help many users!
