### ISSUE TITLE
Paprika import failed `KeyError: 'description'`

### ISSUE THREAD

**Issue by Aohzan** [vabene1111/recipes#573]
### Version
Version: 0.15.2 and build from `develop` branch

### Bug description
I try to import Paprika recipes and I get this error each times:
```
172.18.0.1 - - [21/Apr/2021:21:28:07 +0200] "POST /import/ HTTP/1.0" 302 0 "https://mywebsite/import/" "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/recipes/cookbook/integration/integration.py", line 112, in do_import
    recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
  File "/opt/recipes/cookbook/integration/paprika.py", line 23, in get_recipe_from_file
    name=recipe_json['name'].strip(), description=recipe_json['description'].strip(),
KeyError: 'description'
```

I tried to change by `description=recipe_json['description'].strip(),` by `description='',` but same error

I export from iOS Paprika app.

Have you an idea to fix this ?

Thanks :)

**Comment by vabene1111** [comment]
yes that is fixable basically by putting the description a variable first surrounded by a KeyError exception block. I can fix that for the next update. 

Would you mind sending me your paprika export so i can see why it does not contain a description field ? because all the data from paprika i have worked with so far always included it but maybe the IOS export has differences.

if you dont want to post it publicly feel free to send it to info@tandoor.dev

**Comment by Aohzan** [comment]
Hello
I sent it to your email address, thanks

**Comment by vabene1111** [comment]
awesome, will take a look later

**Comment by vabene1111** [comment]
ok so thanks for the sample data, the import will be fixed with the next update

**Comment by Aohzan** [comment]
Great Thank you!
