### ISSUE TITLE
CSRF token isn't included in api generated from openapi generator

### ISSUE THREAD

**Issue by smilerz** [vabene1111/recipes#579]
### Bug description
I'm not 100% sure that its possible to generate the CSRF config from there - but it seems like the logical location.

**Comment by vabene1111** [comment]
i am not really sure if a CSRF token has anything to do with the openapi generator.

Usually, when using the api from an external client, the CSRF token is not required. If send from a browser (like all the frontend pages do) the CSRF token is included inside of a header that is send along with the request. The header gets its token from a cookie.

What i do not 100% know is how the new system does it, because i did not need to include my old CSRF "hack" in those script files 🤔 maybe axios can automatically detect the CSRF cookie and include it in their requests. I guess it would be good to verify this behavior django should thrown an error if no token is present in web based requests

**Comment by smilerz** [comment]
You are right - that wouldn't make a ton of sense.  Your CookLog API is using CSRF token for that purpose, I just assumed that the openapi methods would follow the same pattern.  I'm reworking the Keyword page following a similar approach as the searchv2 page and stumbled on authentication so just copied the method that you used on the older API.  If you preferred that it be in the html template I can move it.

**Comment by vabene1111** [comment]
there are some rather old legacy api methods in the api.py file which a really stupid. They were either really quick hacks for problems i did not want to find a proper solution for or i was to dumb back then to know any better. For all api needs please only use the DRF methods the only exception being super special stuff like the ical thingy that probably also has better solutions. 

I think the keyword page is a really good page to get startet to try out the vue frontend system. Just a little warning i am currently trying to upgrade the django webpack loading system which might cause some compatibility issues, feel free to message me if you get any issues after merging my changes (if i get them to work)

**Comment by vabene1111** [comment]
ok so finally got it to work. Basically the only change for you really is that `{% render_bundle 'chunk-vendors' %}` is no longer required because the view render already includes the required chunks (i need to implement splitting at some point but that is also taken care of then). 

If you have any questions let me know

**Comment by smilerz** [comment]
> For all api needs please only use the DRF methods the only exception being super special stuff like the ical thingy that probably also has better solutions.

That's been my approach unless its been a django backend API.  and thanks for the update on the webpacks - I'll rebase with the new updates.

**Comment by vabene1111** [comment]
Ok perfect, I will close this for now, if you have any further questions let me know
