### ISSUE TITLE
Feedback please !!

### ISSUE THREAD

**Issue by vabene1111** [vabene1111/recipes#624]
I want to improve Tandoor where you need it so please feel free share some insights on how you use Tandoor!

Either fill out this [Google Form](https://forms.gle/qNfLK2tWTeWHe9Qd7) or reply to this issue.

**Comment by smilerz** [comment]
I have a list of things on my wishlist that I'm hoping to get to eventually:
Heirarchical Ingredients
Faceted Search
What Can I Make Now? (including on-hand inventory)
Better ingredient/unit matching on import
Custom word replacement on import (e.g. 'grams' automatically imported as 'g')
improved ingredient parser (items in parens moved to notes)
quick view ingredients
quick view associated recipe
favorite recipes
alexa shopping list integration

**Comment by vabene1111** [comment]
i guess most of these points are on my list as well 😂 apart from that the survey is primarily aimed at finding out what current features are used so that i can decide whether to improve those or start work on new ones.

**Comment by MJWherry** [comment]
Maybe a 'Todays Meals' page where it shows grouped by meal types the meals scheduled for today, would like to make a shortcut on our echo show so that we can just click when we go to cook and it brings us to the scheduled recipe

**Comment by vabene1111** [comment]
nice idea! the new search that will be released as beta likeley today or this week has a feature to show the meals planned for the day at the top of the search. But some dedicated "kiosk mode" pages would be somethign pretty cool as well i guess.

**Comment by MJWherry** [comment]
Also a couple of other thoughts

-maybe a link when creating a meal plan to see an image of the meal?
-also, ingredient groups? creating a shopping list exports to a list awesome but usually when we make them we group ingredients like protein, dairy, fruits/veggies, etc, right now we are just doing it manually but it would save some time at least for us

Thank you again for the development, great web app!

**Comment by vabene1111** [comment]
what exactly do you mean by you do it manually ? there are groups supportet but currently it is only possible to add them trough the admin. I am currently working on building a management UI for the supermarkets and their categories. Or do you mean that tandoor should come with a database of ingredient->category mappings ?

**Comment by philip-n** [comment]
*Just installed Tandoor, so the following is the intended usage rather than real experience.*

**Main goal** Set up meal plans for the coming week and easily create shopping lists. Allow one person at home to make last minute adjustments to the shopping list while another person is en route to the supermarket.

**Usage** on PC / tablet / phone. No smart speakers, no need for stock keeping (I assume the time spent on tracking purchases and logging which "in stock" goods are used would be greater than the time saved on checking what's available).

**Additional goals / feature requests** that I think I haven't seen mentioned in other issues:
* Discoverability of recipes:
  * see what one has not cooked for a long time (i.e. list recipes by "last logged" date)
  * "kiosk" view (think: tablet) where one swipes through all the recipes in arbitrary order, until one hits a "That's what I like today" moment
* PDF export of recipes (single or batch)
  * so one can easily send some recipe by mail or messenger ("This tasted great, can you send me the recipe?")
  * to be able to select some recipes in advance (e.g. for a trip w/o Tandoor access) and save or print them
* adding an attachment to the recipe (e.g. the scan of the original recipe, to compare it with the current edited version; or because it is in grandmas handwriting, ...)

**Additional goals / feature requests** that already exist (at least in a similar form):
* Allow to add kitchen equipment to recipes (needs wok, needs big pan, ...). Of course one can add it to the recipe text, but this feels kinda wrong.

**Comment by vabene1111** [comment]
closing this issue to have it gone from the list but please always feel free to submit feedback here or trough the form :)

The individual topics will be addressed over the next updates
