### ISSUE TITLE
Meal plan sharing across user/groups

### ISSUE THREAD

**Issue by MJWherry** [vabene1111/recipes#638]
I'm testing this as a replacement for blue apron/hello fresh for me and my fiancé, was looking at the meal planning and the grocery list generation. 

If i'm adding in meal plan type for a user in the default space, then I had assumed those meal plan types would be shard for all users in that space. What i'm trying to do is to add meal plan types (lunch and dinner) so that we both can see it them when creating a meal plan so when i make a meal plan on my account, she can see the meal plan on her account also (we take turns choosing the weekly meals and the opposite when cooking). I thought about just creating a shared account but if we like this enough and my friends/family like this idea I planned on adding on to my external hosted setup and creating accounts for them. Is it possible to share meal plan types and meal plans across users?

**Comment by vabene1111** [comment]
yes it is possible, sadly the documentation realy sucks and the UI isn't really clear about it ...

1. Create the same meals on each account that wants to share (same name)
2. go to settings and enter you friends, family, fiance to the "default share" list

After that meal plan entries and shopping lists should be shared between you two automatically

**Comment by Crazyphil** [comment]
I'm confused by the current implementation of shared meal plans as well.

I have the same use case as @MJWherry. We want to enter recipes into the meal plan and other users of the same space should see them. I cannot find any settings @vabene1111 suggested for "default sharing" (version 1.0.5.2), so we always add the other user to the sharing field of the meal plan entry.

The bigger concern, however, is that meal types seem to be user-specific instead of space-specific. Every user has to add their own meal types, because otherwise they aren't even able to save entries (the meal type dropdown is empty if a user doesn't have their own types). This clutters the meal plan, because either every user configures icons and background colors the same, or else entried added by different users are shown completely differently and the calendar gets confusing.

Am I missing some configuration? Why aren't meal types shared objects like ingredients and units and, basically, everything else?

**Comment by smilerz** [comment]
The settings to share by default are in the settings page
![image](https://user-images.githubusercontent.com/1808639/153897027-ce8f4132-5933-41a1-8016-ef28c742cd48.png)
