### ISSUE TITLE
Docker Tag

### ISSUE THREAD

**Issue by Tuetenk0pp** [vabene1111/recipes#643]
I noticed that the `latest` docker tag isn't the latest anymore. Is that intentional? 😉

**Comment by vabene1111** [comment]
no, the run failed for some reason just with that action .. hope it goes trough this time, for some reason, even though the configs are the same ...

**Comment by vabene1111** [comment]
will keep this open until its resoved

**Comment by MaxJa4** [comment]
The tagged version works fine at least - I was impatient and tried it with that :)

Btw... is it possible here on GitHub to add external workers to potentially speed up the building process (maybe also other things)? Not complaining, but since I have a private GitLab instance, maybe I could share some resources that way and shorten the release process and other things.

**Comment by vabene1111** [comment]
interesting idea 🤔 

what really confuses me is that the same run just sometimes works and sometimes failes, even though dockerfile and CI files are basically identical. The build times are reasonable but maybe we can see if we can improve this in the future

**Comment by MaxJa4** [comment]
Just did some research. Doesn't work with GitLab easily, but I could deploy a shared GitHub Actions Runner, which can be linked to this repo, it's officially supported. The runner would e.g. be inside a docker container itself, so it'd be a controlled environment.
If you feel like you'd benefit from it (with the initial setup work in mind), then feel free to hit me up :)

**Comment by vabene1111** [comment]
ok thanks. For now there are some more important things on my list but i will message you if i need improvements on the CI setup.

Other than that the original issue seems to be resolved with the latest action run
