### ISSUE TITLE
Cannot use Log Cooking from overview

### ISSUE THREAD

**Issue by Forceu** [vabene1111/recipes#646]
### Version
Version: 0.16.0

### Bug description
The Log Cooking feature cannot be used from the overview, but works when actually displaying a recipe.

![image](https://user-images.githubusercontent.com/1593467/120683812-5aab8880-c49e-11eb-9d29-d4f810421344.png)

![image](https://user-images.githubusercontent.com/1593467/120683856-64cd8700-c49e-11eb-997d-c840dd77b04c.png)

> Uncaught ReferenceError: rating is not defined
>     at HTMLInputElement.<anonymous> ((index):3771)
>     at HTMLInputElement.dispatch (jquery-3.5.1.min.dc5e7f18c8d3.js:2)
>     at HTMLInputElement.v.handle (jquery-3.5.1.min.dc5e7f18c8d3.js:2)
> (anonymous) @ (index):3771
> dispatch @ jquery-3.5.1.min.dc5e7f18c8d3.js:2
> v.handle @ jquery-3.5.1.min.dc5e7f18c8d3.js:2

**Comment by vabene1111** [comment]
ok, i might have forgotten some include, thanks for reporting

**Comment by Forceu** [comment]
@vabene1111 This issue seems to be still present in 0.16.7

**Comment by vabene1111** [comment]
that is intersting, should have been fixed in ef200a42831b80c3c92ba5e0d6c43d1619294f0d 

Can you reload your browser without cache (shift +F5 on windows/linux) to verify that it is not a javascript caching issue because i have just tested it in my local environment on master and on my personal instance running the latest dev image an both work without problems (even without invalidating any caches) .

**Comment by Forceu** [comment]
I just had a closer look at the problem and it seems that the issue has only been fixed for the search style "New", but not "Small" or "Large", which I am using.

**Comment by vabene1111** [comment]
ah ok, yes that might be the case. The "old" views (small/large) are going to be deprecated (once the new one has some styling options) at some point and use an old version of the cook log modal. 

I will see that it is fixed anyway.

May i ask why you prefer the "old" style so that i can improve the new one ?

**Comment by Forceu** [comment]
The new style doesn't sort the list alphabetically and also doesn't display page numbers on the main page, which I prefer. 

Also I like having a vertical list with the rating and last cook log, which (as far as I know) is not displayed in the new overview. Personally I only use the view "Large"

**Comment by vabene1111** [comment]
ok thanks for the feedback

- the times, last cook date and rating are coming to the new search and are not yet implemented #556 
- I will also take note of the following layout preferences that could be implemented for the new search
    - "wide style" (one card per row)
    - pagination style (allow to choose between endless scroll and pagination or maybe even revert back because endless scroll causes some other issues
- sorting should be alphabetical with the exception of new recipes being ranked first which should probably be an option

**Comment by vabene1111** [comment]
fixed in old layout, everything else is listed in some other issue
