### ISSUE TITLE
Broken import on specific chefkoch.de recipe

### ISSUE THREAD

**Issue by philip-n** [vabene1111/recipes#666]
**Is your feature request related to a problem? Please describe.**
When importing a certain recipe from Chefkoch.de, one ingredient was not imported.

**Describe the solution you'd like**
If there is a (potential) error during import, display some information so that the user can check manually.

Reason: If URL import results in a seemingly correct result (e.g. long list of ingredients and the full textual description), it's easy to assume that everything went well.

**Describe alternatives you've considered**
*none*

**Additional context**
On https://www.chefkoch.de/rezepte/804871184310070/Brokkoli-Bratlinge.html , the eggs in the ingredients list are a hyperlink for some reason. They were missing after import.

**Comment by smilerz** [comment]
I can look at this and see where the failure is occurring.  

If it is in tandoor I'll fix if possible and add a test case for this scenario, otherwise it will need to be handled upstream in recipe_scrapers.

In general though, given the huge number of ways that imports can fail, I'm not 100% sure we can notify if a specific ingredient is missed (or any other failure/attribute for that matter.)

**Comment by vabene1111** [comment]
you are probably right. The old importer handled ingredients that were not parsable (which seems to be the case here) by showing the "raw" above a row of empty or wrongly filled inputs. But if recipe-scrapers completely removes those lines we are probably not able to do much about it

**Comment by philip-n** [comment]
@smilerz

>  In general though, given the huge number of ways that imports can fail, I'm not 100% sure we can notify if a specific ingredient is missed (or any other failure/attribute for that matter.)

I don't think there is a need for specific notifications. Just a best-effort general warning along the lines of "There might have been a problem during import. Please double-check to make sure that all data is correct (e.g. all ingredients listed with correct amounts, full recipe text imported etc)".

**Comment by smilerz** [comment]
> I don't think there is a need for specific notifications. Just a best-effort general warning along the lines of "There might have been a problem during import. Please double-check to make sure that all data is correct (e.g. all ingredients listed with correct amounts, full recipe text imported etc)".

The good news is that the error is in tandoor and should be fixed today or tomorrow.
The bad news is that the way the import process works every import would report an error - it tries getting data in one method, if that fails tries another, etc, etc so that approach wouldn't work as there isn't any way to determine if the failure was expected or unusual.

**Comment by philip-n** [comment]
Fair enough! Thanks for looking into it and fixing this :+1:
