### ISSUE TITLE
Handling of fractional servings

### ISSUE THREAD

**Issue by philip-n** [vabene1111/recipes#669]
### Version
Version: 0.16.1

### Bug description
Some recipes give only a vague number of servings, like 2 - 3. When trying to enter this into Tandoor, e.g. as `2.5` or `2,5`, import fails because the servings are internally modelled as `int` (see below).

The error message is rather unclear, though: 
![Error_500](https://user-images.githubusercontent.com/3903619/121177650-f736a780-c85d-11eb-940a-74e0f1d75417.png)

I guess it might be possible to just change the servings field type to `float`, to avoid this concrete issue altogether?

Additional generic proposals:
* validate input fields in frontend (prevent sending "malformed" requests to backend)
* if a malformed input arrives, try to give a clearer error message

---

```
ERROR:django.request:Internal Server Error: /data/import/url
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '2,5'
```

**Comment by philip-n** [comment]
I assume that for the calculations, it does not really matter if there is an `int` or `float` to begin with.

It might rather be a philosophical matter - do non-integer servings sizes make sense? Or is 2.5 servings in reality just 3 small ones, or two large ones?

I'm tempted to say that `2.5` means "enough for three people when there's some salad or dessert; enough for 2 hungry people when there is nothing else".

Anyway, I think the error message should become clearer (when I encountered it, I had just manually imported a recipe from HTML-blocks and would have been quite annoyed at getting an error without workaround). Everything else is optional :)

**Comment by vabene1111** [comment]
Honestly this is the reason i did not implement servings for a long time. Even if i follow the amounts specified in a recipe i am sometimes more hungry than others and if a friend of mine eats it he have 6 servings while i have only 3 because i eat more. 

I think input validaation needs to happen on the frontend but other than that i think one should just decide on one serving amount. After that you can still use the log cooking function to have servings calculated based on an average of cooking events (which i think can handle floats but i am not sure).

Apart from that the ability to define an amount, be it servings or ingredients, as a rough estimate would be something nice but i am not really sure on how to implement that on the interface without cluttering it ...

I will leave this issue open at least until i fixed the validation, maybe some interesting ideas come up in the meantime

**Comment by vabene1111** [comment]
ok so i added some automatic rounding on the input as validation outside of real forms is a little tricky, this should prevent obscure error messages for now, this can be properly looked into once the component is migrated to the new frontend
