### ISSUE TITLE
Category for Recipes

### ISSUE THREAD

**Issue by cschoeni** [vabene1111/recipes#687]
**Is your feature request related to a problem? Please describe.**
I always get frustrated when I don't know what to cook. In my previous app (which is really not as good as your web app), I could search by category. E.g. I was craving pasta, so I typed in pasta and all the recipes with the pasta category came up. 

**Describe the solution you'd like**
I am aware that there are tags. However, I think it would be Cool if there was an additional field with categories. A list where you can maintain the categories and then be able to select when you make the recipe.  Maybe it makes sense to keep this as m:n so a recipe can be in multiple categories. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you have considered.
Of course, you could customize the search function to search not only for text in the title but also in the category. 
Or you could search tag: and the respective value. 

Best regards from Switzerland

**Comment by vabene1111** [comment]
Categories were supported in older versions but were removed because it simply doubled the work needed to maintain the same functionality as tags already do. 
There is also a very sophisticated search for tags (especially with the new search) and in an upcoming pr tags can be structured as tress giving you the option to have a root tag "Category" and sub tags like "german", "italian", ...

Categories basically require the exact same functionality to be implemented again which could be done but would remove time spend on other more needed features. 

Let me know if, knowing what you can do with tags, the features fullfill your needs of what you wanted from categories.
