### ISSUE TITLE
 You have reached the maximum number of recipes for your space. 

### ISSUE THREAD

**Issue by GiamBoscaro** [vabene1111/recipes#716]
Hello

I installed Tandoor on my raspberry with docker. Everything works fine but when I try to add a recipe from the web interface, I get the error Y`ou have reached the maximum number of recipes for your space.`. I am logged in with the admin account, and on the space settings have "Recipes 0 to infinity" so I guess I should be good.
If I add the recipe from the Django Administration Panel it works though, and then I can go back to the web interface and edit the recipe.
What am I doing wrong then?

**Comment by vabene1111** [comment]
This sounds like a big in my logic, I will fix this as soon as possible. Sorry for the inconvenience

**Comment by GiamBoscaro** [comment]
No problem, I am not in a hurry! Thanks for you work :)

**Comment by vabene1111** [comment]
do you by chance have a user limit set for your space ? because i just tested with the latest version and everything seems to work.

You can go to admin > Spaces > Your Space (likely default) and post a screenshot of your settings, maybe a migration messed something up.

Can you also verify that you have the latest version running (latest tag on docker hub)

**Comment by GiamBoscaro** [comment]
> 
> 
> do you by chance have a user limit set for your space ? because i just tested with the latest version and everything seems to work.
> 
> You can go to admin > Spaces > Your Space (likely default) and post a screenshot of your settings, maybe a migration messed something up.
> 
> Can you also verify that you have the latest version running (latest tag on docker hub)

`image: vabene1111/recipes:0.16.0`

But you are right. I had the limit set to 0. What confused me is that if I went to Settings > Space Settings there was: Recipes 0 to infinity. So I thought I had no limits. 
As you said, if I go to Settings > Administration > Spaces I see the actual limit of the Default space is 0. I set it to 1000 and now it works, and indeed I now see 0 to 1000 in Space Settings.

**Comment by vabene1111** [comment]
you did everything correctly. Having 0 in the number of recipes allows you to have an infinite amount of recipes. 

I always try that new versions or new features behave exactly like old versions with the default settings. The problem you are having is that you are running `0.16.0` which due to a little oversight on my end contained a bug that did not caluclate the number of recipes correctly.

If you update to latest (0.16.7) this issue is fixed and you can set it back to 0.

Usually it is safe to use latest as your version tag, just the last few 0.16.X releases contained a few bugs but they could all be fixed quickly

**Comment by GiamBoscaro** [comment]
Understood! Downloading the latest version now! Thank you!

**Comment by vabene1111** [comment]
thank you for reporting the issue and enjoy using tandoor :) if you have any further questions or issues feel free to let me know
