### ISSUE TITLE
"I personally prefer to have my data where my docker-compose.yml resides" but then example uses volumes 

### ISSUE THREAD

**Issue by timdonovanuk** [vabene1111/recipes#737]
I too like all my data in one place, not placed all over `/var/lib/docker/volumes/`.

Please consider adding support for bindmounts for the other nginx_config and staticfiles.

Thanks!

**Comment by vabene1111** [comment]
This is possible but does not make sense in case of the staticfiles and requires some configuration in case of the nginx confgig

1. the nginx config directory needs to be a volume because otherwise it cannot contain default data. If you manually copy the nginx directoy from this repo and mount it into both nginx and web container you are find and you can have it as a bind mount. Since this file usually never changes and does not require any modification for 99% of setups it can be left as a volume for most cases. you also dont need to backup it or anything
2. the staticfiles directory does not contain any important files and is just persistently mounted so you dont have to collect all files on every restart. you can safely convert it to a bind mount.
