### ISSUE TITLE
Referencing recipe in steps

### ISSUE THREAD

**Issue by zhorvath83** [vabene1111/recipes#806]
### Version
Version: 0.16.8

### Bug description
- In an existing recipe You can refer to itself as a new step. When you try to delete a circularly referenced recipe, you get a http 500 error. I suggest disabling the circular referencing of recipes.

- When I delete the mistakenly referenced step-recipe, the record was deleted from cookbook_recipe_steps table, but left in cookbook_step table (which consist the circular reference). So the problem became invisible from the UI and left in DB. Is it intentional not to be deleted the record from cookbook_step table?

**Comment by vabene1111** [comment]
hmm interesting. I made it so that circular dependencies could be added but to keep it simple for now only one recipe in depth is loaded from the api upon requesting a recipe. 

In the future i wanted to add a proper check to avoid circular dependencies. 

I will take a look and try to fix your problem, thanks for reporting

**Comment by vabene1111** [comment]
ok the issue was actually related to the label for the recipe not being able to load (independently of the circular reference). I fixed this with a quick workaround for now, this will properly be refactored once i rewrite the recipe editor.

Also: Steps being left in the database is due to DRF not deleting foreign objects when there reference is deleted #854 which is the correct behavior. I think steps should behave this way as we might allow steps to be used in multiple recipes. I think i will build some kind of cleanup page to delete steps/foods/etc. not referenced anywhere
