### ISSUE TITLE
Reverse Proxy/External Authentication

### ISSUE THREAD

**Issue by cazier** [vabene1111/recipes#81]
Feel free to file this issue under the "only affects a few people" category, but I was wondering if you'd be interested in adding functionality to log in using, as Django describes it, [REMOTE_USER](https://docs.djangoproject.com/en/3.0/howto/auth-remote-user/).

My current set up uses nginx as a reverse proxy, and [Authelia](https://github.com/authelia/authelia) as an SSO provider. In short, if I try to use a subdomain that is protected by Authelia, it requires me to a) be logged in, and b) have access (configured in Authelia) for that site.

Django provides the functionality to log-in via a reverse proxy header by using a specific Authentication Backend, and reading the variable passed through the header, simply by adding a few lines in the `settings.py` file and creating a custom middleware. (Though the last step can be optional.)

Is this something you would be willing to implement upstream? I'm happy to create a pull request, but, while I think it's quite basic, I am aware it's not something that would necessarily be applicable to all users.

Thanks!

**Comment by vabene1111** [comment]
That sounds very interesting and also like something many self hosting enthusiasts might already have setup. As i dont have a setup of my own with authelia so feel free to create a PR with something that works for your setup. I think it would be best to have as much of it configurable trough the `.env` file as possible so that people with other auth frameworks can use it as well.

I can then review the code and read up on the docs if there are possible security or feature limitations and then we can merge it.

**Comment by vabene1111** [comment]
so in 0df86b940f2265decb96d75c57a3738c35a2776a i added an online setup page as some people apparently dont have shell access to their containers. I have added a condition so that the page should not be shown if remote userers are activated but please make sure to thoroughly validate this (https://github.com/vabene1111/recipes/commit/0df86b940f2265decb96d75c57a3738c35a2776a#diff-3a3a6e110e53cfdd2cdab24960feb6eeR265).
