### ISSUE TITLE
Translation site is on a rollercoaster

### ISSUE THREAD

**Issue by auanasgheps** [vabene1111/recipes#847]
Hi,
This is not really related to Recipes/Tandoor but to the translation website which I think is hosted by you, https://translate.tandoor.dev/

I've been trying to translate strings in the last two days, but I'm constantly getting this message
![immagine](https://user-images.githubusercontent.com/20586878/131585183-a7cc7197-e5e8-494b-8f74-04e5dc69453f.png)

When the website is up, it is extremely slow and can take 10 seconds to load a page.

It is basically unusable.

Are you aware of these problems?

**Comment by vabene1111** [comment]
yes thank you for reporting this. The VPS running the translation site is a little on the weak side as i wanted to keep the hosting cost down. 

It ususally works quite ok for a while and then suddenly at some point gets very slow, i think i will try integrating it with some better monitoring to notice when it gets down and if that does not help i will need to buy a bigger VPS for the translation system, sorry for your inconvenience.

I am leaving this open so that i remember adding proper monitoring

**Comment by vabene1111** [comment]
ok so interestingly the page was working perfectly fine for me and CPU wasnt even that loaded, i have create a swap file as memory usage was quite high, maybe this caused the server to crash every now and then.

Still going to add it to monitoring to better understand whats happening

**Comment by auanasgheps** [comment]
Thanks for letting me know.

Just wondering if Weblate is free for open source projects, so you don't have to pay a VPS? Other translation platforms have such policy.

**Comment by vabene1111** [comment]
Weblate is not a service but an application you can host yourself (as tandoor)

There are alternatives but Weblate has in my opinion worked best so far

**Comment by auanasgheps** [comment]
Right, I didn't know it had to be self hosted. By the way since you created the swap file the website is working perfectly!

**Comment by rmburg** [comment]
The website only returns 404s again.

**Comment by vabene1111** [comment]
there were some issues with the page why it was offline for a while. I started it again but I am not sure if the issues will come back. Feel free to give it a go.
