### ISSUE TITLE
Link to Recipe

### ISSUE THREAD

**Issue by B5m3M** [vabene1111/recipes#852]
I've come across a feature in Paprika that you can Link to another Recipe in your Recipe Steps. I've not seen this feature here on Tandoor. Also when I import Paprika Recipes - The links I made are simply not links to another recipe anymore but mere normal text. 

It's an advantage when making Bread and you can link all your bread Recipes to the Sourdough Recipe.

**Comment by vabene1111** [comment]
there are currently two methods of linking in tandoor

first the old one, where you open a food and link a recipe to it. this will put the link into the ingredient list of the recipe.
Since one of the latest versions you can also simply set a step to be of type "recipe" and select which recipe you want to link. This recipe will then be expanded on the view page and shown.

The reason paprika links are broken after the import is due to limitations in the data format as far as i remember, but maybe the importer could be improved to handle linked recipes as well.

Hope this helps you, if you have any additional questions let me know
